// Package git provides PR creation for GitHub, GitLab, and Gitea/Forgejo.
// All providers use net/http directly — zero external SDK dependencies.
package git

import (
	"bytes"
	"context"
	"crypto/rand"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

// Provider creates pull requests on a git host.
type Provider interface {
	// CreatePR opens a pull request that creates or updates a single file.
	// repo is in "owner/name" format. branch is generated by the implementation.
	CreatePR(ctx context.Context, repo, baseBranch, title, content, targetPath, description string) (prURL, branch string, err error)
}

// New returns a Provider for the given provider type.
// provider is "github", "gitlab", or "gitea". token is the API token.
// baseURL is only used for gitea (the self-hosted instance URL).
func New(provider, token, baseURL string) Provider {
	switch provider {
	case "gitlab":
		return &gitlabProvider{token: token, client: &http.Client{Timeout: 30 * time.Second}}
	case "gitea":
		return &giteaProvider{baseURL: strings.TrimRight(baseURL, "/"), token: token, client: &http.Client{Timeout: 30 * time.Second}}
	default: // github
		return &githubProvider{token: token, client: &http.Client{Timeout: 30 * time.Second}}
	}
}

func genBranch() string {
	b := make([]byte, 6)
	rand.Read(b)
	return "ragamuffin/draft-" + hex.EncodeToString(b)
}

// ── GitHub ──────────────────────────────────────────────────────────────────────

type githubProvider struct {
	token  string
	client *http.Client
}

func (p *githubProvider) apiURL(format string, args ...any) string {
	return "https://api.github.com" + fmt.Sprintf(format, args...)
}

func (p *githubProvider) do(ctx context.Context, method, urlStr string, body any, out any) error {
	var bodyReader io.Reader
	if body != nil {
		b, err := json.Marshal(body)
		if err != nil {
			return fmt.Errorf("marshal: %w", err)
		}
		bodyReader = bytes.NewReader(b)
	}

	req, err := http.NewRequestWithContext(ctx, method, urlStr, bodyReader)
	if err != nil {
		return err
	}
	req.Header.Set("Authorization", "Bearer "+p.token)
	req.Header.Set("Accept", "application/vnd.github+json")
	req.Header.Set("X-GitHub-Api-Version", "2022-11-28")
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}

	resp, err := p.client.Do(req)
	if err != nil {
		return fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		respBody, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("GitHub API %d: %s", resp.StatusCode, string(respBody))
	}

	if out != nil {
		if err := json.NewDecoder(resp.Body).Decode(out); err != nil {
			return fmt.Errorf("decode: %w", err)
		}
	}
	return nil
}

func (p *githubProvider) CreatePR(ctx context.Context, repo, baseBranch, title, content, targetPath, description string) (string, string, error) {
	branch := genBranch()

	// 1. Get base branch SHA
	var refResp struct {
		Object struct {
			SHA string `json:"sha"`
		} `json:"object"`
	}
	if err := p.do(ctx, "GET", p.apiURL("/repos/%s/git/ref/heads/%s", repo, baseBranch), nil, &refResp); err != nil {
		return "", "", fmt.Errorf("get base ref: %w", err)
	}
	baseSHA := refResp.Object.SHA

	// 2. Create branch
	createRef := map[string]any{
		"ref": "refs/heads/" + branch,
		"sha": baseSHA,
	}
	if err := p.do(ctx, "POST", p.apiURL("/repos/%s/git/refs", repo), createRef, nil); err != nil {
		return "", "", fmt.Errorf("create branch: %w", err)
	}

	// 3. Create/update file on branch
	fileReq := map[string]any{
		"message": title,
		"content": base64.StdEncoding.EncodeToString([]byte(content)),
		"branch":  branch,
	}

	// Check if file exists to get SHA for update
	var existing struct {
		SHA string `json:"sha"`
	}
	err := p.do(ctx, "GET", p.apiURL("/repos/%s/contents/%s?ref=%s", repo, targetPath, branch), nil, &existing)
	if err == nil && existing.SHA != "" {
		fileReq["sha"] = existing.SHA
	}

	if err := p.do(ctx, "PUT", p.apiURL("/repos/%s/contents/%s", repo, targetPath), fileReq, nil); err != nil {
		return "", "", fmt.Errorf("create file: %w", err)
	}

	// 4. Handle deletion (empty content)
	if content == "" {
		deleteReq := map[string]any{
			"message": title,
			"sha":     existing.SHA,
			"branch":  branch,
		}
		if err := p.do(ctx, "DELETE", p.apiURL("/repos/%s/contents/%s", repo, targetPath), deleteReq, nil); err != nil {
			return "", "", fmt.Errorf("delete file: %w", err)
		}
	}

	// 5. Create PR
	prReq := map[string]any{
		"title": title,
		"head":  branch,
		"base":  baseBranch,
	}
	if description != "" {
		prReq["body"] = description
	}

	var prResp struct {
		HTMLURL string `json:"html_url"`
	}
	if err := p.do(ctx, "POST", p.apiURL("/repos/%s/pulls", repo), prReq, &prResp); err != nil {
		return "", "", fmt.Errorf("create PR: %w", err)
	}

	return prResp.HTMLURL, branch, nil
}

// ── GitLab ──────────────────────────────────────────────────────────────────────

type gitlabProvider struct {
	token  string
	client *http.Client
}

func (p *gitlabProvider) apiURL(format string, args ...any) string {
	return "https://gitlab.com/api/v4" + fmt.Sprintf(format, args...)
}

func (p *gitlabProvider) do(ctx context.Context, method, urlStr string, body any, out any) error {
	var bodyReader io.Reader
	if body != nil {
		b, err := json.Marshal(body)
		if err != nil {
			return fmt.Errorf("marshal: %w", err)
		}
		bodyReader = bytes.NewReader(b)
	}

	req, err := http.NewRequestWithContext(ctx, method, urlStr, bodyReader)
	if err != nil {
		return err
	}
	req.Header.Set("PRIVATE-TOKEN", p.token)
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}

	resp, err := p.client.Do(req)
	if err != nil {
		return fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		respBody, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("GitLab API %d: %s", resp.StatusCode, string(respBody))
	}

	if out != nil {
		if err := json.NewDecoder(resp.Body).Decode(out); err != nil {
			return fmt.Errorf("decode: %w", err)
		}
	}
	return nil
}

func (p *gitlabProvider) CreatePR(ctx context.Context, repo, baseBranch, title, content, targetPath, description string) (string, string, error) {
	branch := genBranch()
	projectID := url.PathEscape(repo)

	// 1. Create branch
	branchReq := map[string]string{
		"branch": branch,
		"ref":    baseBranch,
	}
	if err := p.do(ctx, "POST", p.apiURL("/projects/%s/repository/branches", projectID), branchReq, nil); err != nil {
		return "", "", fmt.Errorf("create branch: %w", err)
	}

	// 2. Create commit with file action
	action := "create"
	if content == "" {
		action = "delete"
	}

	commitReq := map[string]any{
		"branch":         branch,
		"commit_message": title,
		"actions": []map[string]any{
			{
				"action":    action,
				"file_path": targetPath,
				"content":   content,
			},
		},
	}
	if err := p.do(ctx, "POST", p.apiURL("/projects/%s/repository/commits", projectID), commitReq, nil); err != nil {
		return "", "", fmt.Errorf("create commit: %w", err)
	}

	// 3. Create merge request
	mrReq := map[string]any{
		"title":         title,
		"source_branch": branch,
		"target_branch": baseBranch,
	}
	if description != "" {
		mrReq["description"] = description
	}

	var mrResp struct {
		WebURL string `json:"web_url"`
	}
	if err := p.do(ctx, "POST", p.apiURL("/projects/%s/merge_requests", projectID), mrReq, &mrResp); err != nil {
		return "", "", fmt.Errorf("create MR: %w", err)
	}

	return mrResp.WebURL, branch, nil
}

// ── Gitea / Forgejo ─────────────────────────────────────────────────────────────

type giteaProvider struct {
	baseURL string
	token   string
	client  *http.Client
}

func (p *giteaProvider) apiURL(format string, args ...any) string {
	return p.baseURL + fmt.Sprintf(format, args...)
}

func (p *giteaProvider) do(ctx context.Context, method, urlStr string, body any, out any) error {
	var bodyReader io.Reader
	if body != nil {
		b, err := json.Marshal(body)
		if err != nil {
			return fmt.Errorf("marshal: %w", err)
		}
		bodyReader = bytes.NewReader(b)
	}

	req, err := http.NewRequestWithContext(ctx, method, urlStr, bodyReader)
	if err != nil {
		return err
	}
	req.Header.Set("Authorization", "Bearer "+p.token)
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}

	resp, err := p.client.Do(req)
	if err != nil {
		return fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	// Gitea can return 409 if branch already exists — not an error for us
	if resp.StatusCode >= 400 && resp.StatusCode != 409 {
		respBody, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("Gitea API %d: %s", resp.StatusCode, string(respBody))
	}

	if out != nil {
		if err := json.NewDecoder(resp.Body).Decode(out); err != nil {
			return fmt.Errorf("decode: %w", err)
		}
	}
	return nil
}

func (p *giteaProvider) CreatePR(ctx context.Context, repo, baseBranch, title, content, targetPath, description string) (string, string, error) {
	branch := genBranch()
	apiBase := p.apiURL("/api/v1")

	// 1. Get base branch SHA
	var branchResp struct {
		Commit struct {
			SHA string `json:"sha"`
		} `json:"commit"`
	}
	if err := p.do(ctx, "GET", apiBase+"/repos/"+repo+"/branches/"+baseBranch, nil, &branchResp); err != nil {
		return "", "", fmt.Errorf("get base branch: %w", err)
	}

	// 2. Create branch
	branchReq := map[string]any{
		"old_branch_name": baseBranch,
		"new_branch_name": branch,
	}
	if err := p.do(ctx, "POST", apiBase+"/repos/"+repo+"/branches", branchReq, nil); err != nil {
		return "", "", fmt.Errorf("create branch: %w", err)
	}

	// 3. Create/update file
	fileReq := map[string]any{
		"message": title,
		"content": base64.StdEncoding.EncodeToString([]byte(content)),
		"branch":  branch,
	}

	var existing struct {
		SHA string `json:"sha"`
	}
	err := p.do(ctx, "GET", apiBase+"/repos/"+repo+"/contents/"+targetPath+"?ref="+branch, nil, &existing)
	if err == nil && existing.SHA != "" {
		fileReq["sha"] = existing.SHA
	}

	if content != "" {
		if err := p.do(ctx, "PUT", apiBase+"/repos/"+repo+"/contents/"+targetPath, fileReq, nil); err != nil {
			return "", "", fmt.Errorf("create file: %w", err)
		}
	} else if existing.SHA != "" {
		deleteReq := map[string]any{
			"message": title,
			"sha":     existing.SHA,
			"branch":  branch,
		}
		if err := p.do(ctx, "DELETE", apiBase+"/repos/"+repo+"/contents/"+targetPath, deleteReq, nil); err != nil {
			return "", "", fmt.Errorf("delete file: %w", err)
		}
	}

	// 4. Create PR
	prReq := map[string]any{
		"title": title,
		"head":  branch,
		"base":  baseBranch,
	}
	if description != "" {
		prReq["body"] = description
	}

	var prResp struct {
		HTMLURL string `json:"html_url"`
	}
	if err := p.do(ctx, "POST", apiBase+"/repos/"+repo+"/pulls", prReq, &prResp); err != nil {
		return "", "", fmt.Errorf("create PR: %w", err)
	}

	return prResp.HTMLURL, branch, nil
}
